Repository boostcamp-2020/Project11-B-Web-FE-Performance-Monitoring-Server, pull requests merged in 2020-12, with the labels that each got.

#64 프로젝트 생성 api
  .eslintrc
  src/models/project.ts
  src/routes/project/controllers/createProject.ts
  src/routes/project/controllers/index.ts
  src/routes/project/router.ts
Labels: api, server, 🛠feature

#62 메일 발송
  package-lock.json
  package.json
  src/models/Invite.ts
  src/routes/test/controllers/acceptInvite.ts
  src/routes/test/controllers/sendInvite.ts
  src/routes/test/controllers/sendMail.ts
  src/routes/test/router.ts
  src/utils/mailTemplate/common/footer.ts
  src/utils/mailTemplate/common/header.ts
  src/utils/mailTemplate/inviteMember.ts
  src/utils/sendMail.ts
Labels: server, 🛠feature

#125 Project soft delete / owner 변경 수정 / crime list api
  src/models/Crime.ts
  src/models/Issue.ts
  src/models/Project.ts
  src/models/sampleCrimes.ts
  src/routes/crime/controllers/addCrime.ts
  src/routes/crime/controllers/devAddIssues.ts
  src/routes/crime/controllers/devDeleteIssues.ts
  src/routes/crime/controllers/getCrimes.ts
  src/routes/crime/controllers/index.ts
  src/routes/crime/router.ts
  src/routes/issue/controllers/getIssues.ts
  src/routes/project/controllers/deleteProject.ts
  src/routes/project/controllers/getProject.ts
  src/routes/project/controllers/getProjects.ts
  src/routes/project/controllers/updateProjectOwner.ts
  src/routes/project/service/ownserService.ts
  src/routes/test/controllers/addUsers.ts
  src/utils/authMiddleware.ts
Labels: server
